server:
  port: 8080

spring:
  webflux:
    static-path-pattern: /static/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping : debug
