server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: qwerty
    key-alias: test_key
    key-store-type: PKCS12

spring:
  webflux:
    static-path-pattern: /static/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping : debug
